[project]
name = "lmmarket"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "nltk>=3.9.1",
    "openai>=1.97.0",
    "pandas>=2.3.1",
    "sentence-transformers>=5.0.0",
]
